#!/usr/bin/env bash
# Interactive .env generator for Fluxo

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(repo_root)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

ENV_FILE="${ROOT}/.env"
EXAMPLE="${ROOT}/.env.example"

if [[ ! -f "$EXAMPLE" ]]; then
    log_err ".env.example not found at ${EXAMPLE}"
    exit 1
fi

if [[ -f "$ENV_FILE" ]] && ! confirm ".env already exists. Overwrite?"; then
    log_warn "Aborted."
    exit 0
fi

log_info "Fluxo environment setup (values from apps/api/src/utils/env.ts schema)"
echo

NODE_ENV="$(prompt_default "NODE_ENV" "production")"
PORT="$(prompt_default "PORT" "5001")"
FRONTEND_URL="$(prompt_default "FRONTEND_URL" "http://localhost:5000")"
API_URL="$(prompt_default "API_URL" "http://localhost:5001")"
APP_NAME="$(prompt_default "APP_NAME" "Fluxo")"

if confirm "Auto-generate ENCRYPTION_KEY?"; then
    ENCRYPTION_KEY="$(gen_secret_hex)"
    log_ok "Generated ENCRYPTION_KEY"
else
    ENCRYPTION_KEY="$(prompt_default "ENCRYPTION_KEY" "change-me-32-byte-key")"
fi

if confirm "Auto-generate SESSION_SECRET?"; then
    SESSION_SECRET="$(gen_secret_base64)"
    log_ok "Generated SESSION_SECRET"
else
    SESSION_SECRET="$(prompt_default "SESSION_SECRET" "change-me-session-secret")"
fi

SESSION_LIFETIME="$(prompt_default "SESSION_LIFETIME (seconds)" "604800")"
BCRYPT_ROUNDS="$(prompt_default "BCRYPT_ROUNDS" "10")"

DB_USER="$(prompt_default "PostgreSQL user" "fluxo")"
if confirm "Auto-generate PostgreSQL password?"; then
    DB_PASSWORD="$(gen_secret_base64 | tr -d '/+=' | head -c 32)"
    log_ok "Generated DB password"
else
    DB_PASSWORD="$(prompt_secret "PostgreSQL password")"
fi
DB_NAME="$(prompt_default "PostgreSQL database" "fluxo")"
DB_HOST="$(prompt_default "PostgreSQL host" "127.0.0.1")"
DB_PORT="$(prompt_default "PostgreSQL port" "5432")"
POSTGRES_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

REDIS_HOST="$(prompt_default "REDIS_HOST" "127.0.0.1")"
REDIS_PASSWORD="$(prompt_default "REDIS_PASSWORD (use 'null' for none)" "null")"
REDIS_PORT="$(prompt_default "REDIS_PORT" "6379")"

DISCORD_CLIENT_ID="$(prompt_default "DISCORD_CLIENT_ID" "your-discord-client-id")"
DISCORD_CLIENT_SECRET="$(prompt_secret "DISCORD_CLIENT_SECRET")"
DISCORD_REDIRECT_URI="$(prompt_default "DISCORD_REDIRECT_URI" "${API_URL}/api/v1/discord/callback")"

NEXT_PUBLIC_API_URL="$(prompt_default "NEXT_PUBLIC_API_URL" "${API_URL}/api/v1")"

SMTP_HOST="$(prompt_default "SMTP_HOST (optional, empty to skip)" "")"
SMTP_PORT=""
SMTP_USER=""
SMTP_PASS=""
EMAIL_FROM=""
if [[ -n "$SMTP_HOST" ]]; then
    SMTP_PORT="$(prompt_default "SMTP_PORT" "587")"
    SMTP_USER="$(prompt_default "SMTP_USER" "")"
    SMTP_PASS="$(prompt_secret "SMTP_PASS")"
    EMAIL_FROM="$(prompt_default "EMAIL_FROM" "noreply@example.com")"
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
NODE_ENV=${NODE_ENV}
PORT=${PORT}
FRONTEND_URL=${FRONTEND_URL}
API_URL=${API_URL}
APP_NAME=${APP_NAME}

ENCRYPTION_KEY=${ENCRYPTION_KEY}
SESSION_SECRET=${SESSION_SECRET}
SESSION_LIFETIME=${SESSION_LIFETIME}
BCRYPT_ROUNDS=${BCRYPT_ROUNDS}

POSTGRES_URL=${POSTGRES_URL}

REDIS_HOST=${REDIS_HOST}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_PORT=${REDIS_PORT}

DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}

NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
EOF

if [[ -n "$SMTP_HOST" ]]; then
    cat >>"$ENV_FILE" <<EOF

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
EMAIL_FROM=${EMAIL_FROM}
EOF
fi

chmod 600 "$ENV_FILE"
log_ok "Wrote ${ENV_FILE}"
log_warn "Store DB password securely: ${DB_PASSWORD}"
